default: &default
  options:
    raise_not_found_error: false
development:
  <<: *default
  sessions:
    default:
      database: body-weights-dev
      hosts:
        - localhost:27017
production:
  <<: *default
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
